### ISSUE TITLE
Tutorial for create pages and blog posts

### ISSUE THREAD

**Issue by auh83** [pydanny/fastapi-blog#32]
Hi Danny,

Congrats for your "fastapi-blog" project, I would like to integrate it in my website. Is there a tutorial to understand how to create pages and blog posts ?

**Comment by pydanny** [comment]
This is a fantastic ticket! I'm on it!

**Comment by auh83** [comment]
Thank you @pydanny I will try to integrate your fastapi-blog in my project

**Comment by pydanny** [comment]
Just added the pages entry into the README. Good luck!

At some point I'll really document this project, for now I'm just working on core features and architecture.

**Comment by pydanny** [comment]
@auh83 there's a rather nasty bug in static files. Please give me a day or two to work it out.

**Comment by auh83** [comment]
> @auh83 there's a rather nasty bug in static files. Please give me a day or two to work it out.

No problem

**Comment by pydanny** [comment]
@auh83 I've decided to archive this repo to work on [FastHTML](https://www.fastht.ml/).
